### ISSUE TITLE
Should there be a list of endpointURLs for a Dataservice?

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/datacatalogtordf#10]
Currently, the class implementing a Dataservice only accepts one endpointURL:
https://github.com/Informasjonsforvaltning/datacatalogtordf/blob/87b2602c51890cf5505e58f73543f7c68284ea9d/src/datacatalogtordf/dataservice.py#L37

While the proposal for DCAT-AP-NO has multiplicity 1..n:
https://informasjonsforvaltning.github.io/dcat-ap-no/#datatjeneste-endepunktsurl

This is also in accordance with the need to list a set of server-urls (production, test etc) in FDK.

**Comment by stigbd** [comment]
Short answer: no, since this will break maxCardinality restriction of W3C DCAT 2:
```
dcat:DataService
  a owl:Class ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:maxCardinality "1"^^xsd:nonNegativeInteger ;
      owl:onProperty dcat:endpointURL ;
    ] 
.
```
ref: https://www.w3.org/ns/dcat2.ttl

See the discussion on https://github.com/SEMICeu/DCAT-AP/issues/166#issuecomment-707842634

**Comment by stigbd** [comment]
Closes this, since the implementation is in accordance with the 1..1 cardinality of dcat-ap-no v2 which has been released last week.
https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-endepunktsurl
