### ISSUE TITLE
Add support for owl:sameAs in Agent

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/datacatalogtordf#17]
In the Agent class there is need for expressing that this agent is the same as another resource.

_Originally posted by @frederik-ronnevig in https://github.com/Informasjonsforvaltning/modelldcatnotordf/pull/17#discussion_r521330160_

**Comment by frederik-ronnevig** [comment]
Lukker denne fordi det er allerede implementert og merget
