### ISSUE TITLE
Feil return type i to_rdf()

### ISSUE THREAD

**Issue by Chlenix** [Informasjonsforvaltning/datacatalogtordf#20]
`to_rdf` lover å returnere en `str`
https://github.com/Informasjonsforvaltning/datacatalogtordf/blob/6565f2b36297aad7e938b133f94a82ffc73640cd/src/datacatalogtordf/catalog.py#L168-L175

Men denne gir tilbake en byte array `bytes`:
https://github.com/Informasjonsforvaltning/datacatalogtordf/blob/6565f2b36297aad7e938b133f94a82ffc73640cd/src/datacatalogtordf/catalog.py#L193-L195

**Comment by stigbd** [comment]
Resolved in #22

**Comment by frederik-ronnevig** [comment]
Er dette noe som også vil være aktuelt for modelldcatnotordf?

**Comment by stigbd** [comment]
Ja, dette trur eg er gjennomgåande for alle biblioteka våre.

**Comment by stigbd** [comment]
Ja, dette trur eg er gjennomgåande for alle biblioteka våre.
