### ISSUE TITLE
Legge til støtte for (vcard:Kind)

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/datacatalogtordf#24]
https://data.norge.no/specification/dcat-ap-no/#klasse-kontaktopplysning

**Comment by stigbd** [comment]
vcard:Kind er allereie støtta ved at dette biblioteket gjenbruker klassen `Contact` frå concepttordf, ref 
https://concepttordf.readthedocs.io/en/latest/reference.html#module-concepttordf.contact

Dette vil trippel av typen vcard:Organization, som er ei subklasse av vcard:Kind, ref https://www.w3.org/TR/2014/NOTE-vcard-rdf-20140522/#d4e1819
