### ISSUE TITLE
Skolemisering

### ISSUE THREAD

**Issue by frederik-ronnevig** [Informasjonsforvaltning/datacatalogtordf#30]
Gjelder følgende noder som brukes i modelldcatno:
- Agent (denne ligger i dcat og må håndteres der)
- creator: str (utgår fordi_creator serialiseres av superklassen Resource i dcat)

https://github.com/Informasjonsforvaltning/modelldcatnotordf/issues/86

TODO - gjelder både klasser og Object Properties (som ikke kun kan være blank nodes):

- [x] Agent
- [x] Catalog
- [x] Catalogrecord
- [x] Dataservice
- [x] Dataset
- [x] Distribution
- [x] Document
- [x] Location
- Periodoftime (utgår fordi har ikke identifier og kan bare være blank node og har ingen object properties)
- [x] Relationship
- Resource (utgår fordi den er en abstrakt klasse og dermed ikke instansieres)

Kommentar fra @stigbd :

Dette gjelder for alle klasser i biblioteket. Samtidig bør vi vurdere å opne opp for at biblioteket støtter at klasser ikkje får tildelt indentifikator av bruker, som dermed resulterer i blanke noder.

Derfor blir dette eigentleg to features:

støtte blanke noder for alle (?) klasser,
for alle blanke noder, lag skolem-uris.
Ellers må vi forsøke å implementere dette utan at det resulterer i breaking changes, viss mulig.

**Comment by stigbd** [comment]
Dette gjelder for alle klasser i biblioteket. Samtidig bør vi vurdere å opne opp for at biblioteket støtter at klasser ikkje får tildelt indentifikator av bruker, som dermed resulterer i blanke noder. 

Derfor blir dette eigentleg to features:
- støtte blanke noder for alle (?) klasser,
- for alle blanke noder, lag skolem-uris.

Ellers må vi forsøke å implementere dette utan at det resulterer i breaking changes, viss mulig.

**Comment by frederik-ronnevig** [comment]
Da skal dette være ferdiggstilt. Det som er gjennomført er følgende:

Alle klasser som kan instansieres har fått skolemisering, med unntak av de som kun kan være blanke noder. For eksempel slik som PeriodOfTime. Disse har i tilegg ingen Object Properties, kun Data Properties

Alle endringene er bakoverkompatible. Alle endringene er releaset til v1.4.6
