### ISSUE TITLE
Adding a DataService to a Catalog as a Dataset should give an error or warning

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/datacatalogtordf#5]
After defining a DataService, if trying to add it to a catalog using Catalog.Dataset.append() should give an error or warning, as it leads to mismatch with the specification of range of dcat:dataset (dcat:Dataset) in the DCAT-standard

**Comment by stigbd** [comment]
After considering different approaches to this, I have come to the following:
- Appending an element of wrong type, will raise an error by static type checkers, e.g. mypy
- Enforcing _runtime_ validation of appending element to the list adds complexity, _and_ there seems to me to be that all possibilities will imply that static type checker no longer will raise error.

I therefore prefer to not support this at the moment, and encourage users to use static type checkers to sanitize their code.
